# For more information: https://laravel.com/docs/marketplace
version: '3.8'
services:

    marketplace:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: marketplace
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            XDEBUG_MODE: '${marketplace_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${marketplace_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html/marketplace'
        networks:
            - marketplace
        depends_on:
            - mariadb
            - mailpit

    mariadb:
        image: 'mariadb:10'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'yousef'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'marketplace'
            MYSQL_USER: 'yousef'
            MYSQL_PASSWORD: 'yousef'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mariadb:/var/lib/mysql'
        networks:
            - marketplace
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        networks:
            - marketplace
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - marketplace

    maxscale:
        image: mariadb/maxscale:6.2.3
        ports:
            - 4006:4006 # readwrite port
            - 4008:4008 # readonly port
            - 8989:8989 # REST API port
        networks:
            - marketplace

networks:
    marketplace:
#        driver: overlay
        external: true

volumes:
    mariadb:
        driver: local
    redis:
        driver: local
